Vagrant.configure("2") do |config|

  # Run `vagrant rsync-auto` to sync the shared directory automatically
  config.vm.synced_folder "..", "/vagrant", type: "rsync"

  config.vm.define "main" do |main|
    main.vm.box = "ubuntu/xenial64"
    main.vm.network "private_network", ip: "10.10.10.10"
    main.vm.hostname = "main"

    main.vm.provider "virtualbox" do |vb|
      vb.name = "main"
    end

    main.vm.provision :salt do |salt|

      salt.masterless = true
      salt.minion_config = "minion"
      salt.run_highstate = true
      salt.colorize = false

    end
  end

end
